package adminhandler_test

// End-to-end coverage for the admin client registry against a real PostgreSQL and
// Redis, through real HTTP requests.
//
// The point of this file is the one path production could not reach before: a
// client_secret that was actually generated by the registration endpoint,
// authenticating at the real token endpoint. Every other test for that branch has to
// insert a hash by hand, which proves the verifier works but not that the two halves
// agree. If the registration endpoint stored a hash the token endpoint cannot verify,
// only this test would notice.
//
// It also covers the consequence of disabling a client, which spans three packages:
// the admin service revokes, the repository writes the outbox row, and the OAuth
// middleware and token endpoint have to stop honoring what was already issued.

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"

	oauthredis "github.com/NJUPT-SAST/sast-link-backend-v2/internal/adapter/redis/oauth"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/auth"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/migration"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/model"
	internalredis "github.com/NJUPT-SAST/sast-link-backend-v2/internal/redis"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/repository"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/service/adminclient"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/service/adminuser"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/service/oauth"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/testutil"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/web/adminhandler"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/web/middleware"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/web/oauthhandler"
)

const (
	adminE2EIssuer      = "https://link.sast.fun/v2"
	adminE2ERedirectURI = "https://rp.admin-e2e.test/callback"
	adminE2EVerifier    = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk"
	adminE2EConsentURL  = "https://link.sast.fun/oauth/consent"
)

type adminE2EHarness struct {
	router   *gin.Engine
	database *gorm.DB
	user     *model.User
	admin    *model.User
}

func setupAdminE2E(t *testing.T) *adminE2EHarness {
	t.Helper()
	gin.SetMode(gin.TestMode)

	databaseURL := testutil.StartPostgres(t)
	instance, err := migration.New(databaseURL)
	if err != nil {
		t.Fatalf("create migration: %v", err)
	}
	t.Cleanup(func() { _, _ = instance.Close() })
	if migrateErr := instance.Up(); migrateErr != nil {
		t.Fatalf("apply migrations: %v", migrateErr)
	}
	database := testutil.OpenGORM(t, databaseURL)
	store := internalredis.Store{
		Client: testutil.StartRedis(t),
		Keys:   internalredis.NewKeys("sastlink:admin-e2e"),
	}

	_, key, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generate signing key: %v", err)
	}
	jwtManager := &auth.JWTManager{
		Issuer:   adminE2EIssuer,
		Audience: []string{"sast-link-v2"},
		Active:   auth.JWTKeyPair{KID: "admin-e2e", Private: key},
	}
	refreshManager, err := auth.NewRefreshTokenManager("0123456789abcdef0123456789abcdef", nil)
	if err != nil {
		t.Fatalf("construct refresh manager: %v", err)
	}

	users := repository.NewUser(database)
	admin := adminE2EUser("admin-e2e@njupt.edu.cn", "B24040301", model.UserRoleAdmin)
	if err := users.CreateWithProfile(context.Background(), admin, &model.Profile{}); err != nil {
		t.Fatalf("create admin user: %v", err)
	}
	user := adminE2EUser("subject-e2e@njupt.edu.cn", "B24040302", model.UserRoleMember)
	if err := users.CreateWithProfile(context.Background(), user, &model.Profile{}); err != nil {
		t.Fatalf("create subject user: %v", err)
	}

	clients := repository.NewOAuthClient(database)
	tokens := repository.NewToken(database)
	blacklist := oauthredis.BlacklistStore{Store: store}
	auditLog := repository.NewAuditLog(database)

	oauthService := oauth.Service{
		Users:          users,
		Clients:        clients,
		Authorizations: repository.NewOAuthAuthorization(database),
		Tokens:         tokens,
		Audit:          auditLog,
		Profiles:       users,
		Requests:       oauthredis.AuthorizeRequestStore{Store: store},
		Blacklist:      blacklist,
		JWT:            jwtManager,
		RefreshTokens:  refreshManager,
		AccessTTL:      time.Hour,
		RefreshTTL:     30 * 24 * time.Hour,
		CodeTTL:        5 * time.Minute,
		RequestTTL:     10 * time.Minute,
		Issuer:         adminE2EIssuer,
	}
	adminService := adminclient.Service{
		Clients:   clients,
		Blacklist: blacklist,
		Audit:     auditLog,
		Secrets:   auth.ClientSecretHasher{},
	}
	adminUserService := adminuser.Service{
		Users:     users,
		Audit:     auditLog,
		Blacklist: blacklist,
	}

	router := gin.New()
	oauthhandler.RegisterRoutes(router, oauthhandler.Handler{
		Service: oauthService,
		// The auth-state cache is deliberately enabled, not nil: the deletion test's
		// post-delete 401 must come from the tombstone invalidation path (revoked in
		// the delete transaction, cached as a miss, DB row gone), not merely from the
		// CASCADE having removed the authoritative row. Leaving the cache off would
		// make that assertion true for the wrong reason.
		Auth: middleware.Authenticator{
			JWT:            jwtManager,
			Tokens:         tokens,
			AuthStateCache: store,
			AuthStateTTL:   5 * time.Second,
		},
		ConsentURL: adminE2EConsentURL,
	}, func(c *gin.Context) {
		middleware.SetPrincipal(c, middleware.Principal{UserID: user.ID, JTI: "admin-e2e-consent"})
		c.Next()
	})
	// The scope and role gates are covered in middleware and cmd/api; here the admin
	// is simply present and permitted, so the registry behavior is what is under test.
	allow := func(c *gin.Context) { c.Next() }
	adminhandler.RegisterRoutes(router, adminhandler.Handler{
		Clients:   adminService,
		Users:     adminUserService,
		AuditLogs: adminUserService,
	}, adminhandler.Gates{
		RequireAuth: func(c *gin.Context) {
			middleware.SetPrincipal(c, middleware.Principal{
				UserID: admin.ID, Role: string(model.UserRoleAdmin), JTI: "admin-e2e",
			})
			c.Next()
		},
		RequireReadScope:  allow,
		RequireWriteScope: allow,
		RequireAdmin:      allow,
		RequireReader:     allow,
	})

	return &adminE2EHarness{router: router, database: database, user: user, admin: admin}
}

func adminE2EUser(email, studentID string, role model.UserRole) *model.User {
	return &model.User{
		Name:         "管理端到端",
		PhoneNumber:  "1380013" + studentID[len(studentID)-4:],
		QQNumber:     studentID,
		PasswordHash: "password-hash",
		LoginEmail:   email,
		StudentID:    studentID,
		Role:         role,
		State:        model.UserStateOnSAST,
		EmailType:    model.EmailTypeNJUpt,
		College:      model.CollegeOther,
	}
}

func (h *adminE2EHarness) do(t *testing.T, method, target, contentType, body string) *httptest.ResponseRecorder {
	t.Helper()
	var reader *strings.Reader
	if body != "" {
		reader = strings.NewReader(body)
	}
	var request *http.Request
	if reader == nil {
		request = httptest.NewRequestWithContext(context.Background(), method, target, nil)
	} else {
		request = httptest.NewRequestWithContext(context.Background(), method, target, reader)
	}
	if contentType != "" {
		request.Header.Set("Content-Type", contentType)
	}
	recorder := httptest.NewRecorder()
	h.router.ServeHTTP(recorder, request)
	return recorder
}

// registerClient registers a confidential client and returns its client_id, the
// plaintext secret the endpoint issued, and its primary key.
func (h *adminE2EHarness) registerClient(t *testing.T) (clientID, secret string, primaryKey int64) {
	t.Helper()
	recorder := h.do(t, http.MethodPost, "/admin/oauth-clients", "application/json",
		`{"client_name":"E2E Registered","client_type":"third_party",`+
			`"redirect_uris":["`+adminE2ERedirectURI+`"],`+
			`"grant_types":["authorization_code","refresh_token"],`+
			`"scopes":["openid","profile"]}`)
	if recorder.Code != http.StatusCreated {
		t.Fatalf("register status = %d, want 201: %s", recorder.Code, recorder.Body.String())
	}
	var body struct {
		Data struct {
			ID           int64  `json:"id"`
			ClientID     string `json:"client_id"`
			ClientSecret string `json:"client_secret"`
		} `json:"data"`
	}
	if err := json.Unmarshal(recorder.Body.Bytes(), &body); err != nil {
		t.Fatalf("decode register body: %v", err)
	}
	if body.Data.ClientID == "" || body.Data.ClientSecret == "" || body.Data.ID == 0 {
		t.Fatalf("register response missing identity fields: %s", recorder.Body.String())
	}
	return body.Data.ClientID, body.Data.ClientSecret, body.Data.ID
}

// authorizeAndConsent walks both authorize legs for clientID and returns the code.
func (h *adminE2EHarness) authorizeAndConsent(t *testing.T, clientID string) string {
	t.Helper()
	challenge, err := auth.PKCEChallengeS256(adminE2EVerifier)
	if err != nil {
		t.Fatalf("compute challenge: %v", err)
	}
	query := url.Values{
		"response_type":         {"code"},
		"client_id":             {clientID},
		"redirect_uri":          {adminE2ERedirectURI},
		"scope":                 {"openid profile"},
		"state":                 {"admin-e2e-state"},
		"code_challenge":        {challenge},
		"code_challenge_method": {"S256"},
	}
	recorder := h.do(t, http.MethodGet, "/oauth/authorize?"+query.Encode(), "", "")
	if recorder.Code != http.StatusFound {
		t.Fatalf("authorize status = %d, want 302: %s", recorder.Code, recorder.Body.String())
	}
	location, err := url.Parse(recorder.Header().Get("Location"))
	if err != nil {
		t.Fatalf("parse consent redirect: %v", err)
	}
	requestID := location.Query().Get("request_id")
	if requestID == "" {
		t.Fatalf("authorize redirect carries no request_id: %s", location)
	}
	consent := h.do(t, http.MethodPost, "/oauth/authorize/consent", "application/json",
		`{"request_id":"`+requestID+`","approve":true}`)
	if consent.Code != http.StatusOK {
		t.Fatalf("consent status = %d, want 200: %s", consent.Code, consent.Body.String())
	}
	var body struct {
		Data struct {
			RedirectURI string `json:"redirect_uri"`
		} `json:"data"`
	}
	if decodeErr := json.Unmarshal(consent.Body.Bytes(), &body); decodeErr != nil {
		t.Fatalf("decode consent body: %v", decodeErr)
	}
	redirect, err := url.Parse(body.Data.RedirectURI)
	if err != nil {
		t.Fatalf("parse client redirect: %v", err)
	}
	code := redirect.Query().Get("code")
	if code == "" {
		t.Fatalf("consent redirect carries no code: %s", body.Data.RedirectURI)
	}
	return code
}

func (h *adminE2EHarness) redeem(t *testing.T, clientID, secret, code string) *httptest.ResponseRecorder {
	t.Helper()
	form := url.Values{
		"grant_type":    {"authorization_code"},
		"code":          {code},
		"redirect_uri":  {adminE2ERedirectURI},
		"client_id":     {clientID},
		"client_secret": {secret},
		"code_verifier": {adminE2EVerifier},
	}
	return h.do(t, http.MethodPost, "/oauth/token", "application/x-www-form-urlencoded", form.Encode())
}

// A secret issued by the registration endpoint must authenticate at the token
// endpoint. This is the seam no unit test can check: registration hashes and stores,
// the token endpoint reads and verifies, and only a real round trip proves the two
// agree on the encoding. Before these endpoints existed, production had no way to
// produce a confidential client at all, so this branch was reachable only from
// fixtures.
func TestAdminE2ERegisteredSecretAuthenticatesAtTokenEndpoint(t *testing.T) {
	testutil.RequireProvider(t)
	h := setupAdminE2E(t)

	clientID, secret, _ := h.registerClient(t)
	code := h.authorizeAndConsent(t, clientID)

	recorder := h.redeem(t, clientID, secret, code)
	if recorder.Code != http.StatusOK {
		t.Fatalf("token status = %d, want 200 with the issued secret: %s",
			recorder.Code, recorder.Body.String())
	}
	var token struct {
		AccessToken string `json:"access_token"`
		TokenType   string `json:"token_type"`
	}
	if err := json.Unmarshal(recorder.Body.Bytes(), &token); err != nil {
		t.Fatalf("decode token body: %v", err)
	}
	if token.AccessToken == "" || token.TokenType != "Bearer" {
		t.Fatalf("token response = %+v", token)
	}
}

// The plaintext must not be recoverable afterwards: only its hash is stored, so a
// database read must not yield anything that can be replayed as the credential.
func TestAdminE2ESecretIsStoredHashedAndNotListed(t *testing.T) {
	testutil.RequireProvider(t)
	h := setupAdminE2E(t)

	_, secret, primaryKey := h.registerClient(t)

	var stored model.OAuthClient
	if err := h.database.Where("id = ?", primaryKey).First(&stored).Error; err != nil {
		t.Fatalf("load stored client: %v", err)
	}
	if stored.ClientSecretHash == nil {
		t.Fatal("no secret hash was persisted")
	}
	if *stored.ClientSecretHash == secret {
		t.Fatal("the plaintext secret was stored")
	}
	if err := auth.VerifyClientSecret(secret, *stored.ClientSecretHash); err != nil {
		t.Fatalf("stored hash does not verify the issued secret: %v", err)
	}
	// The list endpoint must never echo it back.
	listed := h.do(t, http.MethodGet, "/admin/oauth-clients", "", "")
	if listed.Code != http.StatusOK {
		t.Fatalf("list status = %d: %s", listed.Code, listed.Body.String())
	}
	if strings.Contains(listed.Body.String(), secret) ||
		strings.Contains(listed.Body.String(), *stored.ClientSecretHash) {
		t.Fatalf("list response exposed secret material: %s", listed.Body.String())
	}
}

// Disabling a client must stop what it already holds, not just what it asks for
// next. This spans three packages: the admin service asks for revocation, the
// repository does it atomically with the flag flip, and the token endpoint has to
// refuse the refresh token afterwards.
func TestAdminE2EDisablingClientRevokesIssuedTokens(t *testing.T) {
	testutil.RequireProvider(t)
	h := setupAdminE2E(t)

	clientID, secret, primaryKey := h.registerClient(t)
	code := h.authorizeAndConsent(t, clientID)
	redeemed := h.redeem(t, clientID, secret, code)
	if redeemed.Code != http.StatusOK {
		t.Fatalf("token status = %d: %s", redeemed.Code, redeemed.Body.String())
	}
	var token struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	if err := json.Unmarshal(redeemed.Body.Bytes(), &token); err != nil {
		t.Fatalf("decode token body: %v", err)
	}

	disable := h.do(t, http.MethodPut, "/admin/oauth-clients/"+strconv.FormatInt(primaryKey, 10),
		"application/json", `{"is_active":false}`)
	if disable.Code != http.StatusOK {
		t.Fatalf("disable status = %d, want 200: %s", disable.Code, disable.Body.String())
	}
	if !strings.Contains(disable.Body.String(), "撤销") {
		t.Fatalf("disable response does not report revocation: %s", disable.Body.String())
	}

	// The access token row is revoked in the database.
	var revoked int64
	if err := h.database.Model(&model.OAuthAccessToken{}).
		Where("client_id = ? AND revoked_at IS NOT NULL", primaryKey).
		Count(&revoked).Error; err != nil {
		t.Fatalf("count revoked access tokens: %v", err)
	}
	if revoked == 0 {
		t.Fatal("disabling the client revoked no access tokens")
	}

	// And the refresh token can no longer be exchanged, so the client cannot simply
	// renew its way past the revocation.
	refresh := h.do(t, http.MethodPost, "/oauth/token", "application/x-www-form-urlencoded",
		url.Values{
			"grant_type":    {"refresh_token"},
			"refresh_token": {token.RefreshToken},
			"client_id":     {clientID},
			"client_secret": {secret},
		}.Encode())
	if refresh.Code == http.StatusOK {
		t.Fatalf("refresh succeeded after the client was disabled: %s", refresh.Body.String())
	}
}

// A client disabled through the console must also stop being able to start a new
// authorization, or the operator's action would only be half effective.
func TestAdminE2EDisabledClientCannotAuthorize(t *testing.T) {
	testutil.RequireProvider(t)
	h := setupAdminE2E(t)

	clientID, _, primaryKey := h.registerClient(t)
	if recorder := h.do(t, http.MethodPut, "/admin/oauth-clients/"+strconv.FormatInt(primaryKey, 10),
		"application/json", `{"is_active":false}`); recorder.Code != http.StatusOK {
		t.Fatalf("disable status = %d: %s", recorder.Code, recorder.Body.String())
	}

	challenge, err := auth.PKCEChallengeS256(adminE2EVerifier)
	if err != nil {
		t.Fatalf("compute challenge: %v", err)
	}
	recorder := h.do(t, http.MethodGet, "/oauth/authorize?"+url.Values{
		"response_type":         {"code"},
		"client_id":             {clientID},
		"redirect_uri":          {adminE2ERedirectURI},
		"scope":                 {"openid"},
		"state":                 {"s"},
		"code_challenge":        {challenge},
		"code_challenge_method": {"S256"},
	}.Encode(), "", "")
	// The failure reports invalid_client, and crucially it must land on the
	// first-party consent page rather than the caller-supplied redirect_uri: a
	// disabled client is precisely the case where an unverified URI must not receive
	// the browser, or this endpoint would be an open redirector.
	if recorder.Code != http.StatusFound {
		t.Fatalf("authorize status = %d, want 302 to the consent page: %s",
			recorder.Code, recorder.Body.String())
	}
	location, err := url.Parse(recorder.Header().Get("Location"))
	if err != nil {
		t.Fatalf("parse error redirect: %v", err)
	}
	consent, err := url.Parse(adminE2EConsentURL)
	if err != nil {
		t.Fatalf("parse consent URL: %v", err)
	}
	if location.Host != consent.Host || location.Path != consent.Path {
		t.Fatalf("authorize error went to %q, want the first-party consent page", location)
	}
	if location.Query().Get("error") != "invalid_client" {
		t.Fatalf("error = %q, want invalid_client", location.Query().Get("error"))
	}
	// No authorization code may exist for a disabled client.
	var codes int64
	if err := h.database.Model(&model.OAuthAuthorization{}).
		Where("client_id = ?", primaryKey).Count(&codes).Error; err != nil {
		t.Fatalf("count authorization codes: %v", err)
	}
	if codes != 0 {
		t.Fatalf("authorization codes = %d for a disabled client, want none", codes)
	}
}

// Registration must refuse a dangerous callback all the way through the stack, not
// only in the service's unit tests.
func TestAdminE2ERejectsDangerousRedirectURI(t *testing.T) {
	testutil.RequireProvider(t)
	h := setupAdminE2E(t)

	recorder := h.do(t, http.MethodPost, "/admin/oauth-clients", "application/json",
		`{"client_name":"Evil","client_type":"third_party",`+
			`"redirect_uris":["javascript:alert(document.domain)"],`+
			`"grant_types":["authorization_code"],"scopes":["openid"]}`)
	if recorder.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400: %s", recorder.Code, recorder.Body.String())
	}
	var count int64
	if err := h.database.Model(&model.OAuthClient{}).
		Where("client_name = ?", "Evil").Count(&count).Error; err != nil {
		t.Fatalf("count clients: %v", err)
	}
	if count != 0 {
		t.Fatal("a client with a javascript: redirect URI was persisted")
	}
}

// Closing an account through the console must end the sessions it already holds.
// That consequence spans three packages: the admin service asks for the revocation,
// the repository writes the token rows and the outbox entry in one transaction, and
// the OAuth layer has to stop honoring what was already issued. A unit test with a
// fake repository proves the service asked; only this proves it happened.
func TestAdminE2EClosingAccountRevokesUserTokens(t *testing.T) {
	testutil.RequireProvider(t)
	h := setupAdminE2E(t)

	clientID, secret, _ := h.registerClient(t)
	code := h.authorizeAndConsent(t, clientID)
	redeemed := h.redeem(t, clientID, secret, code)
	if redeemed.Code != http.StatusOK {
		t.Fatalf("token status = %d: %s", redeemed.Code, redeemed.Body.String())
	}
	var token struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	if err := json.Unmarshal(redeemed.Body.Bytes(), &token); err != nil {
		t.Fatalf("decode token body: %v", err)
	}

	// The token works before the account is closed, so the assertion afterwards is
	// about the closure and not about the token never having been valid.
	before := h.userInfo(t, token.AccessToken)
	if before.Code != http.StatusOK {
		t.Fatalf("userinfo before closing = %d, want 200: %s", before.Code, before.Body.String())
	}

	target := strconv.FormatInt(h.user.ID, 10)
	closed := h.do(t, http.MethodDelete, "/admin/users/"+target, "", "")
	if closed.Code != http.StatusOK {
		t.Fatalf("delete status = %d, want 200: %s", closed.Code, closed.Body.String())
	}

	var revoked int64
	if err := h.database.Model(&model.OAuthAccessToken{}).
		Where("user_id = ? AND revoked_at IS NOT NULL", h.user.ID).
		Count(&revoked).Error; err != nil {
		t.Fatalf("count revoked access tokens: %v", err)
	}
	if revoked == 0 {
		t.Fatal("closing the account revoked no access tokens")
	}

	// The issued access token is no longer accepted.
	after := h.userInfo(t, token.AccessToken)
	if after.Code == http.StatusOK {
		t.Fatalf("userinfo still succeeded after the account was closed: %s", after.Body.String())
	}

	// And the refresh token cannot renew past the closure.
	refresh := h.do(t, http.MethodPost, "/oauth/token", "application/x-www-form-urlencoded",
		url.Values{
			"grant_type":    {"refresh_token"},
			"refresh_token": {token.RefreshToken},
			"client_id":     {clientID},
			"client_secret": {secret},
		}.Encode())
	if refresh.Code == http.StatusOK {
		t.Fatalf("refresh succeeded after the account was closed: %s", refresh.Body.String())
	}

	// Restoring returns the account to njupter, and the revoked tokens stay revoked:
	// the owner signs in again rather than resuming the old session.
	restored := h.do(t, http.MethodPut, "/admin/users/"+target+"/restore", "", "")
	if restored.Code != http.StatusOK {
		t.Fatalf("restore status = %d, want 200: %s", restored.Code, restored.Body.String())
	}
	var reloaded model.User
	if err := h.database.First(&reloaded, h.user.ID).Error; err != nil {
		t.Fatalf("reload user: %v", err)
	}
	if reloaded.State != model.UserStateNJUPTer {
		t.Fatalf("state after restore = %q, want njupter", reloaded.State)
	}
	if stillValid := h.userInfo(t, token.AccessToken); stillValid.Code == http.StatusOK {
		t.Fatal("the pre-closure access token works again after restore; revocation must be permanent")
	}
}

// The console's write endpoints and the audit query must agree: an administrative
// action has to be visible in the trail the console reads back.
func TestAdminE2EAdminActionsAppearInTheAuditLog(t *testing.T) {
	testutil.RequireProvider(t)
	h := setupAdminE2E(t)

	target := strconv.FormatInt(h.user.ID, 10)
	updated := h.do(t, http.MethodPut, "/admin/users/"+target, "application/json",
		`{"name":"审计测试","major":"软件工程"}`)
	if updated.Code != http.StatusOK {
		t.Fatalf("update status = %d, want 200: %s", updated.Code, updated.Body.String())
	}

	listed := h.do(t, http.MethodGet, "/admin/audit-logs?action=admin_user_update", "", "")
	if listed.Code != http.StatusOK {
		t.Fatalf("audit list status = %d, want 200: %s", listed.Code, listed.Body.String())
	}
	var payload struct {
		Data struct {
			Logs []struct {
				Action     string          `json:"action"`
				Resource   string          `json:"resource"`
				ResourceID *string         `json:"resource_id"`
				UserID     *int64          `json:"user_id"`
				Success    bool            `json:"success"`
				Detail     json.RawMessage `json:"detail"`
			} `json:"logs"`
			Total int64 `json:"total"`
		} `json:"data"`
	}
	if err := json.Unmarshal(listed.Body.Bytes(), &payload); err != nil {
		t.Fatalf("decode audit list: %v", err)
	}
	if payload.Data.Total != 1 || len(payload.Data.Logs) != 1 {
		t.Fatalf("audit logs = %+v (total %d), want the single update",
			payload.Data.Logs, payload.Data.Total)
	}
	entry := payload.Data.Logs[0]
	if entry.Resource != "user" || entry.ResourceID == nil || *entry.ResourceID != target {
		t.Fatalf("entry = %+v, want it to name the edited user", entry)
	}
	if entry.UserID == nil || *entry.UserID != h.admin.ID {
		t.Fatalf("entry user_id = %v, want the acting administrator %d", entry.UserID, h.admin.ID)
	}
	if !entry.Success {
		t.Fatal("the successful edit was recorded as a failure")
	}
	detail := string(entry.Detail)
	if !strings.Contains(detail, "name") || !strings.Contains(detail, "major") {
		t.Fatalf("detail = %s, want the changed field names", detail)
	}
	// The submitted values must not be in the trail: it outlives the request and every
	// administrator can read it.
	if strings.Contains(detail, "审计测试") {
		t.Fatalf("detail = %s, want it to omit the submitted value", detail)
	}
}

// userInfo calls the OIDC UserInfo endpoint with a bearer token. It is the cheapest
// real check that an access token is still honored end to end: it authenticates
// inline against the database and the blacklist.
func (h *adminE2EHarness) userInfo(t *testing.T, accessToken string) *httptest.ResponseRecorder {
	t.Helper()
	request := httptest.NewRequestWithContext(context.Background(), http.MethodGet, "/userinfo", nil)
	request.Header.Set("Authorization", "Bearer "+accessToken)
	recorder := httptest.NewRecorder()
	h.router.ServeHTTP(recorder, request)
	return recorder
}

// Deleting a client must cut what it already holds, not just what it asks for
// next. The cascade removes the access-token row the DB-authoritative check
// reads, and the revocation leg invalidates the auth-state cache in the same
// breath, so the token that worked a moment ago is refused on the next request.
func TestAdminE2EDeletingClientCutsRedeemedTokens(t *testing.T) {
	testutil.RequireProvider(t)
	h := setupAdminE2E(t)

	clientID, secret, primaryKey := h.registerClient(t)
	code := h.authorizeAndConsent(t, clientID)
	redeemed := h.redeem(t, clientID, secret, code)
	if redeemed.Code != http.StatusOK {
		t.Fatalf("token status = %d: %s", redeemed.Code, redeemed.Body.String())
	}
	var token struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	if err := json.Unmarshal(redeemed.Body.Bytes(), &token); err != nil {
		t.Fatalf("decode token body: %v", err)
	}
	// The token authenticates before the deletion.
	if recorder := h.userInfo(t, token.AccessToken); recorder.Code != http.StatusOK {
		t.Fatalf("userinfo before delete status = %d, want 200: %s", recorder.Code, recorder.Body.String())
	}

	del := h.do(t, http.MethodDelete, "/admin/oauth-clients/"+strconv.FormatInt(primaryKey, 10), "", "")
	if del.Code != http.StatusOK {
		t.Fatalf("delete status = %d, want 200: %s", del.Code, del.Body.String())
	}
	if !strings.Contains(del.Body.String(), "撤销") {
		t.Fatalf("delete response does not report revocation: %s", del.Body.String())
	}

	// The registration and its token metadata are gone.
	var clientCount int64
	if err := h.database.Model(&model.OAuthClient{}).Where("id = ?", primaryKey).Count(&clientCount).Error; err != nil {
		t.Fatalf("count client: %v", err)
	}
	if clientCount != 0 {
		t.Fatalf("oauth_clients rows after delete = %d, want 0", clientCount)
	}
	var tokenCount int64
	if err := h.database.Model(&model.OAuthAccessToken{}).Where("client_id = ?", primaryKey).Count(&tokenCount).Error; err != nil {
		t.Fatalf("count access tokens: %v", err)
	}
	if tokenCount != 0 {
		t.Fatalf("oauth_access_tokens rows after delete = %d, want 0", tokenCount)
	}

	// The redeemed token is refused on the very next request: the DB-authoritative
	// check finds no row, and the auth-state cache was invalidated with it.
	if recorder := h.userInfo(t, token.AccessToken); recorder.Code != http.StatusUnauthorized {
		t.Fatalf("userinfo after delete status = %d, want 401: %s", recorder.Code, recorder.Body.String())
	}
}

// The batch read returns full records in request order with missing ids absent,
// and the batch role change applies per-item outcomes through the real service —
// a promotion, a missing id, and the audit trail behind both.
func TestAdminE2EBatchReadAndRoleUpdate(t *testing.T) {
	testutil.RequireProvider(t)
	h := setupAdminE2E(t)

	freshman := adminE2EUser("batch-e2e@njupt.edu.cn", "B24040303", model.UserRoleFreshman)
	if err := repository.NewUser(h.database).
		CreateWithProfile(context.Background(), freshman, &model.Profile{}); err != nil {
		t.Fatalf("create freshman: %v", err)
	}

	// Batch read: request order preserved, missing id silently absent.
	ids := strconv.FormatInt(freshman.ID, 10) + "," + strconv.FormatInt(h.admin.ID, 10) + ",999999"
	read := h.do(t, http.MethodGet, "/admin/users/batch?ids="+ids, "", "")
	if read.Code != http.StatusOK {
		t.Fatalf("batch read status = %d, want 200: %s", read.Code, read.Body.String())
	}
	var readPayload struct {
		Data struct {
			Users []struct {
				ID   int64  `json:"id"`
				Role string `json:"role"`
				Name string `json:"name"`
			} `json:"users"`
		} `json:"data"`
	}
	if err := json.Unmarshal(read.Body.Bytes(), &readPayload); err != nil {
		t.Fatalf("decode batch read: %v", err)
	}
	if len(readPayload.Data.Users) != 2 ||
		readPayload.Data.Users[0].ID != freshman.ID || readPayload.Data.Users[1].ID != h.admin.ID {
		t.Fatalf("users = %+v, want [freshman admin] in request order, missing id absent",
			readPayload.Data.Users)
	}
	if readPayload.Data.Users[0].Role != string(model.UserRoleFreshman) ||
		readPayload.Data.Users[1].Role != string(model.UserRoleAdmin) {
		t.Fatalf("roles = %q/%q, want the records' own roles",
			readPayload.Data.Users[0].Role, readPayload.Data.Users[1].Role)
	}

	// Batch role update over a real promotion plus a missing id: 200 overall, with
	// the failure reported per item rather than aborting the batch.
	updated := h.do(t, http.MethodPut, "/admin/users", "application/json",
		`{"ids":[`+strconv.FormatInt(freshman.ID, 10)+`,999999],"role":"member"}`)
	if updated.Code != http.StatusOK {
		t.Fatalf("batch update status = %d, want 200: %s", updated.Code, updated.Body.String())
	}
	var updatePayload struct {
		Data struct {
			Results []struct {
				ID      int64  `json:"id"`
				Success bool   `json:"success"`
				Role    string `json:"role"`
				Reason  string `json:"reason"`
			} `json:"results"`
		} `json:"data"`
	}
	if err := json.Unmarshal(updated.Body.Bytes(), &updatePayload); err != nil {
		t.Fatalf("decode batch update: %v", err)
	}
	if len(updatePayload.Data.Results) != 2 {
		t.Fatalf("results = %d, want 2", len(updatePayload.Data.Results))
	}
	first, second := updatePayload.Data.Results[0], updatePayload.Data.Results[1]
	if !first.Success || first.Role != "member" || first.Reason != "" {
		t.Fatalf("first result = %+v, want success with role member", first)
	}
	if second.Success || second.Reason != "用户不存在" || second.Role != "" {
		t.Fatalf("second result = %+v, want a not-found reason", second)
	}

	var reloaded model.User
	if err := h.database.First(&reloaded, freshman.ID).Error; err != nil {
		t.Fatalf("reload freshman: %v", err)
	}
	if reloaded.Role != model.UserRoleMember {
		t.Fatalf("role = %q, want member after the batch promotion", reloaded.Role)
	}
	if reloaded.TokenVersion != freshman.TokenVersion+1 {
		t.Fatalf("token_version = %d, want %d: a role change must revoke sessions",
			reloaded.TokenVersion, freshman.TokenVersion+1)
	}

	// Both items land in the audit trail with the batch marker.
	audited := h.do(t, http.MethodGet, "/admin/audit-logs?action=admin_user_update", "", "")
	var auditPayload struct {
		Data struct {
			Logs []struct {
				ResourceID *string         `json:"resource_id"`
				Success    bool            `json:"success"`
				Detail     json.RawMessage `json:"detail"`
			} `json:"logs"`
			Total int64 `json:"total"`
		} `json:"data"`
	}
	if err := json.Unmarshal(audited.Body.Bytes(), &auditPayload); err != nil {
		t.Fatalf("decode audit list: %v", err)
	}
	if auditPayload.Data.Total != 2 {
		t.Fatalf("audit total = %d, want 2 (one per id, success and failure)", auditPayload.Data.Total)
	}
	for _, entry := range auditPayload.Data.Logs {
		if !strings.Contains(string(entry.Detail), `"batch":true`) {
			t.Fatalf("audit detail = %s, want the batch marker", entry.Detail)
		}
	}
}
