-- The OAuth client that performed an admin or self-service action. Admin
-- actions likewise run through delegated third-party clients as well as the
-- console, so without this column the two are indistinguishable in the trail.
--
-- Nullable: NULL means no OAuth credential authorized the action (login,
-- registration, reset, the background workers, pre-migration rows), and the
-- 90-day retention ages those NULLs out on its own.
--
-- Plain VARCHAR(255) with no foreign key, so an audit row outlives the
-- registration it names. Named actor_client_id because resource_id already
-- holds a client primary key for the admin_oauth_client_* actions and detail
-- carries a client_id for the OAuth token endpoint. No index yet: about one
-- delegated client exists and idx_audit_logs_action_created covers the common
-- filters. Add one when the filter is in use at volume.
--
-- The migration runner splits statements on semicolons and does not understand
-- comments. A semicolon anywhere above this line would cut the file mid-comment
-- and the remainder would be parsed as SQL.
ALTER TABLE audit_logs ADD COLUMN actor_client_id VARCHAR(255);
