package adminclient

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"

	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/model"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/repository"
	"github.com/NJUPT-SAST/sast-link-backend-v2/internal/scope"
)

// newClientID generates a public client identifier.
//
// Server-generated by design: accepting one from the request would let an
// administrator — or anything that reaches this endpoint — register under an
// identifier that an existing or planned client expects to own, including the
// built-in first-party client that the internal API's azp gate pins to.
func newClientID() (string, error) {
	raw := make([]byte, 16)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("generate client ID: %w", err)
	}
	return hex.EncodeToString(raw), nil
}

// ListClients returns every registration, disabled ones included.
func (s Service) ListClients(ctx context.Context) ([]Client, error) {
	if s.Clients == nil {
		return nil, newError(ErrInternal, "客户端仓储未配置", nil)
	}
	stored, err := s.Clients.List(ctx)
	if err != nil {
		return nil, newError(ErrInternal, "查询 OAuth 客户端失败", err)
	}
	clients := make([]Client, 0, len(stored))
	for i := range stored {
		clients = append(clients, toClient(&stored[i]))
	}
	return clients, nil
}

// CreateClient registers a new OAuth client.
//
// A third_party client gets a generated secret whose plaintext is returned exactly
// once; only the hash is persisted. A first_party client gets none — it is public
// and authenticates with PKCE, matching the built-in client seeded by V003.
func (s Service) CreateClient(ctx context.Context, input CreateClientInput) (*CreateClientResult, error) {
	if s.Clients == nil {
		return nil, newError(ErrInternal, "客户端仓储未配置", nil)
	}
	client, secret, err := s.buildClient(input)
	if err != nil {
		s.auditCreate(ctx, input, nil, false, errorCode(err), 0)
		return nil, err
	}
	if err := s.Clients.Create(ctx, client); err != nil {
		// client_id is generated from 16 random bytes, so a unique violation here is not
		// a caller-visible conflict; it is either a collision that will not recur or a
		// genuine fault. Either way the administrator should retry, not rename.
		s.auditCreate(ctx, input, &client.ClientID, false, ErrInternal.Code, 0)
		return nil, newError(ErrInternal, "创建 OAuth 客户端失败", err)
	}
	s.auditCreate(ctx, input, &client.ClientID, true, 0, 0)
	return &CreateClientResult{Client: toClient(client), ClientSecret: secret}, nil
}

// buildClient validates the input and assembles the row to insert.
func (s Service) buildClient(input CreateClientInput) (*model.OAuthClient, string, error) {
	name, err := validateClientName(input.ClientName)
	if err != nil {
		return nil, "", err
	}
	clientType, err := validateClientType(input.ClientType)
	if err != nil {
		return nil, "", err
	}
	redirectURIs, err := validateRedirectURIs(input.RedirectURIs)
	if err != nil {
		return nil, "", err
	}
	grantTypes, err := validateGrantTypes(input.GrantTypes)
	if err != nil {
		return nil, "", err
	}
	// scope.Normalize is the same gate /oauth/authorize uses, so a registration
	// cannot hold a scope set the authorize endpoint would reject: it rejects
	// unsupported values, duplicates and embedded whitespace, and requires openid.
	scopes, err := scope.Normalize(input.Scopes)
	if err != nil {
		return nil, "", newError(ErrInvalidInput, "scopes 非法，必须包含 openid 且仅含受支持的值", err)
	}
	clientID, err := s.newClientID()
	if err != nil {
		return nil, "", newError(ErrInternal, "生成 client_id 失败", err)
	}
	active := true
	client := &model.OAuthClient{
		ClientID:     clientID,
		ClientName:   name,
		ClientType:   clientType,
		RedirectURIs: redirectURIs,
		GrantTypes:   grantTypes,
		Scopes:       model.StringArray(scopes),
		IsActive:     &active,
	}
	if clientType != model.ClientTypeThirdParty {
		return client, "", nil
	}
	secret, hash, err := s.Secrets.NewClientSecret()
	if err != nil {
		return nil, "", newError(ErrInternal, "生成 client_secret 失败", err)
	}
	client.ClientSecretHash = &hash
	return client, secret, nil
}

// UpdateClient applies a partial update to a registration.
//
// Disabling a client revokes every token issued to it, atomically with the flag
// change. Disabling is a security action and the administrator's expectation is
// that access stops now, not when the last access token happens to expire.
func (s Service) UpdateClient(ctx context.Context, input UpdateClientInput) (*UpdateClientResult, error) {
	if s.Clients == nil {
		return nil, newError(ErrInternal, "客户端仓储未配置", nil)
	}
	if input.ClientPK <= 0 {
		return nil, newError(ErrNotFound, "OAuth 客户端不存在", nil)
	}
	fields, err := s.updateFields(input)
	if err != nil {
		s.auditUpdate(ctx, input, false, errorCode(err), 0, nil)
		return nil, err
	}
	current, err := s.Clients.FindByID(ctx, input.ClientPK)
	if errors.Is(err, repository.ErrNotFound) {
		// Audited like every other rejection on this path: without it, walking primary
		// keys to see which ones exist leaves no trace.
		s.auditUpdate(ctx, input, false, ErrNotFound.Code, 0, nil)
		return nil, newError(ErrNotFound, "OAuth 客户端不存在", nil)
	}
	if err != nil {
		s.auditUpdate(ctx, input, false, ErrInternal.Code, 0, nil)
		return nil, newError(ErrInternal, "查询 OAuth 客户端失败", err)
	}
	// Checked after the row is loaded, because the guard keys on the stored
	// client_id rather than the primary key the caller supplied.
	if protectedErr := s.checkProtected(current, input); protectedErr != nil {
		s.auditUpdate(ctx, input, false, errorCode(protectedErr), 0, &current.ClientID)
		return nil, protectedErr
	}
	// Revocation follows the transition, not the submitted value. Re-sending
	// is_active=false for an already disabled client must not re-revoke, and must not
	// report a fresh revocation to the audit trail.
	revoke := input.IsActive != nil && !*input.IsActive && current.IsActive != nil && *current.IsActive
	now := s.now()
	entries, err := s.Clients.UpdateAndRevoke(ctx, input.ClientPK, fields, revoke, now)
	if errors.Is(err, repository.ErrNotFound) {
		return nil, newError(ErrNotFound, "OAuth 客户端不存在", nil)
	}
	if err != nil {
		s.auditUpdate(ctx, input, false, ErrInternal.Code, 0, &current.ClientID)
		return nil, newError(ErrInternal, "更新 OAuth 客户端失败", err)
	}
	s.deliverBlacklist(ctx, entries, now)
	s.auditUpdate(ctx, input, true, 0, len(entries), &current.ClientID)
	return &UpdateClientResult{RevokedTokens: len(entries)}, nil
}

// updateFields validates the present fields and builds the column map.
func (s Service) updateFields(input UpdateClientInput) (map[string]any, error) {
	fields := make(map[string]any, 3)
	if input.ClientName != nil {
		name, err := validateClientName(*input.ClientName)
		if err != nil {
			return nil, err
		}
		fields["client_name"] = name
	}
	if input.RedirectURIs != nil {
		uris, err := validateRedirectURIs(*input.RedirectURIs)
		if err != nil {
			return nil, err
		}
		fields["redirect_uris"] = uris
	}
	if input.IsActive != nil {
		fields["is_active"] = *input.IsActive
	}
	if len(fields) == 0 {
		return nil, newError(ErrInvalidInput, "没有可更新的字段", nil)
	}
	return fields, nil
}

func toClient(client *model.OAuthClient) Client {
	active := client.IsActive != nil && *client.IsActive
	return Client{
		ID:           client.ID,
		ClientID:     client.ClientID,
		ClientName:   client.ClientName,
		ClientType:   string(client.ClientType),
		RedirectURIs: []string(client.RedirectURIs),
		GrantTypes:   []string(client.GrantTypes),
		Scopes:       []string(client.Scopes),
		IsActive:     active,
		CreatedAt:    client.CreatedAt.UTC(),
		UpdatedAt:    client.UpdatedAt.UTC(),
	}
}

// errorCode extracts the business code from a typed error for the audit trail.
func errorCode(err error) int {
	var typed *Error
	if errors.As(err, &typed) {
		return typed.Code
	}
	return ErrInternal.Code
}
