// Command gen_pinyin_initials generates migration 000017: a stored generated
// column "user".name_initials holding the pinyin initials of name, so the admin
// user list's keyword search can match "lhq" against "刘华强".
//
// The mapping is emitted as one PostgreSQL translate() call whose "from" string
// lists every single-character Han entry go-pinyin knows (default reading,
// heteronyms are not considered) and whose "to" string is the matching initial
// for each. Both strings are equal length, which is what makes the per-character
// translation correct: translate maps the i-th "from" rune to the i-th "to" rune.
//
// Run from this directory:
//
//	go run .
//
// The go-pinyin dependency lives in this nested module so the main module never
// links it at runtime — the pinyin table is baked into the SQL once, and the
// generator is only re-run to change the mapping.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/mozillazg/go-pinyin"
)

const (
	upFile   = "000017_name_initials.up.sql"
	downFile = "000017_name_initials.down.sql"
)

// hanRanges covers the blocks go-pinyin tables are built from: CJK Extension A,
// the CJK Unified Ideographs block, and the CJK Compatibility Ideographs block.
// Characters outside them (Extension B and beyond) are left untranslated by
// translate(), which only degrades to "not findable by initials" — the hanzi
// itself still matches the keyword's name arm, and the name rule accepts those
// blocks, so no completion prompt covers them.
var hanRanges = [][2]rune{
	{0x3400, 0x4DBF},
	{0x4E00, 0x9FFF},
	{0xF900, 0xFAFF},
}

func main() {
	outDir := "../../migrations"
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}

	args := pinyin.NewArgs()
	args.Style = pinyin.FirstLetter

	var from, to strings.Builder
	for _, span := range hanRanges {
		for r := span[0]; r <= span[1]; r++ {
			result := pinyin.Pinyin(string(r), args)
			if len(result) != 1 || len(result[0]) != 1 {
				continue
			}
			initial := result[0][0]
			if len(initial) != 1 || initial[0] < 'a' || initial[0] > 'z' {
				continue
			}
			from.WriteRune(r)
			to.WriteByte(initial[0])
		}
	}

	up := fmt.Sprintf(`-- V017: "user".name_initials, a stored generated column holding the
-- pinyin initials of name (default readings), so the admin user list keyword
-- can match initials like 'lhq' against '刘华强'. Non-Han characters pass
-- through translate() unchanged, so debris names like 'John' become 'john'
-- and stay searchable too. All five interpunct variants the name rule accepts
-- (U+00B7 / U+2027 / U+0387 / U+30FB / U+FF65) plus the ASCII space are
-- stripped first, so '阿依古丽·买买提' yields 'ayglmmt' whatever variant the
-- stored row happens to carry.
-- Generated by scripts/gen_pinyin_initials. Do not edit by hand.
-- Character entries mapped: %d

CREATE FUNCTION sl_name_initials(p_name text) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
    RETURN lower(translate(replace(replace(replace(replace(replace(replace(p_name,
        U&'\00B7', ''), U&'\2027', ''), U&'\0387', ''), U&'\30FB', ''), U&'\FF65', ''), ' ', ''),
        '%s',
        '%s'));

ALTER TABLE "user" ADD COLUMN name_initials VARCHAR(255)
    GENERATED ALWAYS AS (sl_name_initials(name)) STORED;
`, to.Len(), from.String(), to.String())

	down := `-- V017 down: drop the initials column first, then the function once no
-- column references it anymore. The stored data is fully derived from name,
-- so nothing is lost.

ALTER TABLE "user" DROP COLUMN name_initials;

DROP FUNCTION sl_name_initials(text);
`

	for name, content := range map[string]string{upFile: up, downFile: down} {
		path := outDir + "/" + name
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
			os.Exit(1)
		}
	}
	fmt.Printf("wrote %s and %s to %s (%d mapped characters)\n", upFile, downFile, outDir, to.Len())
}
